### PR TITLE
QuizMaker Utility

### PR DESCRIPTION
**Pull request by kareem-ghazi**

### CODE REVIEW

**Comment by kareem-ghazi** [comment]
~~todo: refactor the code a bit for readability in the future.~~

**Comment by kareem-ghazi** [comment]
~~todo: documentation~~

**Comment by kareem-ghazi** [comment]
~~todo: finish up README.md~~

**Comment by Kimosauraus** [comment]
todo: add edit option

**Comment by kareem-ghazi** [comment]
~~issue: after finishing a task, invalid input is considered as the previous option.~~
~~clues: entering a random number fixes it so possibly a scanner may have not been discarded.~~

fixed: apparently, userInput wouldn't clear and it would set it to the previous number (e.g: entering 1 and then after finishing the task, entering invalid input as any character will still set the parsed input to 1 and as a result, have the first option run again for no reason.)

a workaround for this is to set userInput to 0 directly after the program catches the exception. (don't know if this is appropriate but we move.)

**Pull request merged**
